# Generated by Django 5.0.6 on 2024-05-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Lesson',
            new_name='lesson',
        ),
    ]
